services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: "https://vault.cryobs.xyz"
    volumes:
      - /mnt/cryobs/vaultwarden/ww-data:/data/
    ports:
      - 127.0.0.1:8000:80
    networks:
      - cloudflare-net

networks:
  cloudflare-net:
    external: true
